from flask import Flask, render_template, request, send_file
import pdfplumber
import os
from skills import skills_list
from reportlab.pdfgen import canvas

app = Flask(__name__)

UPLOAD_FOLDER = "uploads"
app.config["UPLOAD_FOLDER"] = UPLOAD_FOLDER


@app.route("/")
def home():
    return render_template("index.html")


@app.route("/upload", methods=["POST"])
def upload():

    file = request.files["resume"]

    if file:

        filepath = os.path.join(
            app.config["UPLOAD_FOLDER"],
            file.filename
        )

        file.save(filepath)

        text = ""

        with pdfplumber.open(filepath) as pdf:

            for page in pdf.pages:

                page_text = page.extract_text()

                if page_text:
                    text += page_text

        found_skills = []

        for skill in skills_list:

            if skill.lower() in text.lower():

                found_skills.append(skill)

        total_skills = len(skills_list)

        score = int((len(found_skills) / total_skills) * 100)

        missing_skills = []

        for skill in skills_list:

            if skill not in found_skills:

                missing_skills.append(skill)

        skills_html = ""

        for skill in found_skills:

            skills_html += f"<li>{skill}</li>"
                    
        missing_html = ""

        for skill in missing_skills[:5]:

            missing_html += f"<li>{skill}</li>"

        category = "General"

        if ("html" in text.lower() or
            "css" in text.lower() or
            "javascript" in text.lower() or
            "react" in text.lower()):

            category = "Web Developer"

        elif ("python" in text.lower() and
              "machine learning" in text.lower()):

            category = "Data Scientist"

        elif "python" in text.lower():

            category = "Python Developer"

        elif "java" in text.lower():

            category = "Java Developer"

        ats_message = ""
        ats_color = ""

        if score >= 80:

            ats_message = "Excellent Resume"
            ats_color = "green"

        elif score >= 50:

            ats_message = "Good Resume"
            ats_color = "orange"

        else:

            ats_message = "Needs Improvement"
            ats_color = "red"

        
        return render_template(
    "result.html",
    score=score,
    category=category,
    ats_message=ats_message,
    ats_color=ats_color,
    found_skills=found_skills,
    missing_skills=missing_skills,
    text=text
        )

    from flask import send_file

@app.route("/download-report")
def download_report():

    pdf_file = "resume_report.pdf"

    c = canvas.Canvas(pdf_file)

    c.drawString(100, 800, "Resume Analysis Report")
    c.drawString(100, 770, "Generated by Resume Analyzer")

    c.save()

    return send_file(
        pdf_file,
        as_attachment=True
    )

if __name__ == "__main__":
    app.run(debug=True)